In [14]:
import pandas as pd
import numpy as np
import os

In [2]:
df = pd.read_csv("data/raw/BankChurners.csv")
df

,CLIENTNUM,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,...,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2
0,768805383,Existing Customer,45,M,3,High School,Married,$60K - $80K,Blue,39,...,12691.0,777,11914.0,1.335,1144,42,1.625,0.061,0.000093,0.999910
1,818770008,Existing Customer,49,F,5,Graduate,Single,Less than $40K,Blue,44,...,8256.0,864,7392.0,1.541,1291,33,3.714,0.105,0.000057,0.999940
2,713982108,Existing Customer,51,M,3,Graduate,Married,$80K - $120K,Blue,36,...,3418.0,0,3418.0,2.594,1887,20,2.333,0.000,0.000021,0.999980
3,769911858,Existing Customer,40,F,4,High School,Unknown,Less than $40K,Blue,34,...,3313.0,2517,796.0,1.405,1171,20,2.333,0.760,0.000134,0.999870
4,709106358,Existing Customer,40,M,3,Uneducated,Married,$60K - $80K,Blue,21,...,4716.0,0,4716.0,2.175,816,28,2.500,0.000,0.000022,0.999980
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10122,772366833,Existing Customer,50,M,2,Graduate,Single,$40K - $60K,Blue,40,...,4003.0,1851,2152.0,0.703,15476,117,0.857,0.462,0.000191,0.999810
10123,710638233,Attrited Customer,41,M,2,Unknown,Divorced,$40K - $60K,Blue,25,...,4277.0,2186,2091.0,0.804,8764,69,0.683,0.511,0.995270,0.004729
10124,716506083,Attrited Customer,44,F,1,High School,Married,Less than $40K,Blue,36,...,5409.0,0,5409.0,0.819,10291,60,0.818,0.000,0.997880,0.002118
10125,717406983,Attrited Customer,30,M,2,Graduate,Unknown,$40K - $60K,Blue,36,...,5281.0,0,5281.0,0.535,8395,62,0.722,0.000,0.996710,0.003294
10126,714337233,Attrited Customer,43,F,2,Graduate,Married,Less than $40K,Silver,25,...,10388.0,1961,8427.0,0.703,10294,61,0.649,0.189,0.996620,0.003377

In [3]:
#remoção de colunas desnecessárias e tradução das demais para português
df = df.drop(columns=[
    'CLIENTNUM', 
    'Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1', 
    'Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2'
], errors='ignore')

df = df.rename(columns={
    'Attrition_Flag': 'status_cliente',
    'Customer_Age': 'idade',
    'Gender': 'genero',
    'Dependent_count': 'dependentes',
    'Education_Level': 'escolaridade',
    'Marital_Status': 'estado_civil',
    'Income_Category': 'faixa_renda',
    'Card_Category': 'categoria_cartao',
    'Months_on_book': 'meses_como_cliente',
    'Total_Relationship_Count': 'total_produtos',
    'Months_Inactive_12_mon': 'meses_inativo_12m',
    'Contacts_Count_12_mon': 'contatos_12m',
    'Credit_Limit': 'limite_credito',
    'Total_Revolving_Bal': 'saldo_rotativo',
    'Avg_Open_To_Buy': 'limite_disponivel_medio',
    'Total_Amt_Chng_Q4_Q1': 'var_valor_q4_q1',
    'Total_Trans_Amt': 'valor_total_transacoes',
    'Total_Trans_Ct': 'qtd_total_transacoes',
    'Total_Ct_Chng_Q4_Q1': 'var_qtd_q4_q1',
    'Avg_Utilization_Ratio': 'taxa_utilizacao_credito'
})

df

,status_cliente,idade,genero,dependentes,escolaridade,estado_civil,faixa_renda,categoria_cartao,meses_como_cliente,total_produtos,meses_inativo_12m,contatos_12m,limite_credito,saldo_rotativo,limite_disponivel_medio,var_valor_q4_q1,valor_total_transacoes,qtd_total_transacoes,var_qtd_q4_q1,taxa_utilizacao_credito
0,Existing Customer,45,M,3,High School,Married,$60K - $80K,Blue,39,5,1,3,12691.0,777,11914.0,1.335,1144,42,1.625,0.061
1,Existing Customer,49,F,5,Graduate,Single,Less than $40K,Blue,44,6,1,2,8256.0,864,7392.0,1.541,1291,33,3.714,0.105
2,Existing Customer,51,M,3,Graduate,Married,$80K - $120K,Blue,36,4,1,0,3418.0,0,3418.0,2.594,1887,20,2.333,0.000
3,Existing Customer,40,F,4,High School,Unknown,Less than $40K,Blue,34,3,4,1,3313.0,2517,796.0,1.405,1171,20,2.333,0.760
4,Existing Customer,40,M,3,Uneducated,Married,$60K - $80K,Blue,21,5,1,0,4716.0,0,4716.0,2.175,816,28,2.500,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10122,Existing Customer,50,M,2,Graduate,Single,$40K - $60K,Blue,40,3,2,3,4003.0,1851,2152.0,0.703,15476,117,0.857,0.462
10123,Attrited Customer,41,M,2,Unknown,Divorced,$40K - $60K,Blue,25,4,2,3,4277.0,2186,2091.0,0.804,8764,69,0.683,0.511
10124,Attrited Customer,44,F,1,High School,Married,Less than $40K,Blue,36,5,3,4,5409.0,0,5409.0,0.819,10291,60,0.818,0.000
10125,Attrited Customer,30,M,2,Graduate,Unknown,$40K - $60K,Blue,36,4,3,3,5281.0,0,5281.0,0.535,8395,62,0.722,0.000
10126,Attrited Customer,43,F,2,Graduate,Married,Less than $40K,Silver,25,6,2,4,10388.0,1961,8427.0,0.703,10294,61,0.649,0.189

In [4]:
#tradução dos dados para português
df["status_cliente"] = df["status_cliente"].replace({
    "Existing Customer": "Ativo",
    "Attrited Customer": "Cancelado"
})

df["escolaridade"] = df["escolaridade"].replace({
    "High School": "Ensino Médio",
    "Graduate": "Graduação",
    "Uneducated": "Sem escolaridade",
    "Post-Graduate": "Pós-graduação",
    "College": "Faculdade",
    "Doctorate": "Doutorado",
    "Unknown": "Desconhecido"
})

df["estado_civil"] = df["estado_civil"].replace({
    "Married": "Casado",
    "Single": "Solteiro",
    "Divorced": "Divorciado",
    "Unknown": "Desconhecido"
})

df["faixa_renda"] = df["faixa_renda"].replace({
    "Less than $40K": "Menos de $40 mil",
    "$40K - $60K": "$40 mil - $60 mil",
    "$60K - $80K": "$60 mil - $80 mil",
    "$80K - $120K": "$80 mil - $120 mil",
    "$120K +": "Mais de $120 mil",
    "Unknown": "Desconhecido"
})

df["categoria_cartao"] = df["categoria_cartao"].replace({
    "Blue": "Azul",
    "Silver": "Prata",
    "Gold": "Ouro",
    "Platinum": "Platina"
})

df

,status_cliente,idade,genero,dependentes,escolaridade,estado_civil,faixa_renda,categoria_cartao,meses_como_cliente,total_produtos,meses_inativo_12m,contatos_12m,limite_credito,saldo_rotativo,limite_disponivel_medio,var_valor_q4_q1,valor_total_transacoes,qtd_total_transacoes,var_qtd_q4_q1,taxa_utilizacao_credito
0,Ativo,45,M,3,Ensino Médio,Casado,$60 mil - $80 mil,Azul,39,5,1,3,12691.0,777,11914.0,1.335,1144,42,1.625,0.061
1,Ativo,49,F,5,Graduação,Solteiro,Menos de $40 mil,Azul,44,6,1,2,8256.0,864,7392.0,1.541,1291,33,3.714,0.105
2,Ativo,51,M,3,Graduação,Casado,$80 mil - $120 mil,Azul,36,4,1,0,3418.0,0,3418.0,2.594,1887,20,2.333,0.000
3,Ativo,40,F,4,Ensino Médio,Desconhecido,Menos de $40 mil,Azul,34,3,4,1,3313.0,2517,796.0,1.405,1171,20,2.333,0.760
4,Ativo,40,M,3,Sem escolaridade,Casado,$60 mil - $80 mil,Azul,21,5,1,0,4716.0,0,4716.0,2.175,816,28,2.500,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10122,Ativo,50,M,2,Graduação,Solteiro,$40 mil - $60 mil,Azul,40,3,2,3,4003.0,1851,2152.0,0.703,15476,117,0.857,0.462
10123,Cancelado,41,M,2,Desconhecido,Divorciado,$40 mil - $60 mil,Azul,25,4,2,3,4277.0,2186,2091.0,0.804,8764,69,0.683,0.511
10124,Cancelado,44,F,1,Ensino Médio,Casado,Menos de $40 mil,Azul,36,5,3,4,5409.0,0,5409.0,0.819,10291,60,0.818,0.000
10125,Cancelado,30,M,2,Graduação,Desconhecido,$40 mil - $60 mil,Azul,36,4,3,3,5281.0,0,5281.0,0.535,8395,62,0.722,0.000
10126,Cancelado,43,F,2,Graduação,Casado,Menos de $40 mil,Prata,25,6,2,4,10388.0,1961,8427.0,0.703,10294,61,0.649,0.189

In [9]:
df = df.replace('Desconhecido', np.nan)
df.describe()

,idade,dependentes,meses_como_cliente,total_produtos,meses_inativo_12m,contatos_12m,limite_credito,saldo_rotativo,limite_disponivel_medio,var_valor_q4_q1,valor_total_transacoes,qtd_total_transacoes,var_qtd_q4_q1,taxa_utilizacao_credito
count,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000
mean,46.325960,2.346203,35.928409,3.812580,2.341167,2.455317,8631.953698,1162.814061,7469.139637,0.759941,4404.086304,64.858695,0.712222,0.274894
std,8.016814,1.298908,7.986416,1.554408,1.010622,1.106225,9088.776650,814.987335,9090.685324,0.219207,3397.129254,23.472570,0.238086,0.275691
min,26.000000,0.000000,13.000000,1.000000,0.000000,0.000000,1438.300000,0.000000,3.000000,0.000000,510.000000,10.000000,0.000000,0.000000
25%,41.000000,1.000000,31.000000,3.000000,2.000000,2.000000,2555.000000,359.000000,1324.500000,0.631000,2155.500000,45.000000,0.582000,0.023000
50%,46.000000,2.000000,36.000000,4.000000,2.000000,2.000000,4549.000000,1276.000000,3474.000000,0.736000,3899.000000,67.000000,0.702000,0.176000
75%,52.000000,3.000000,40.000000,5.000000,3.000000,3.000000,11067.500000,1784.000000,9859.000000,0.859000,4741.000000,81.000000,0.818000,0.503000
max,73.000000,5.000000,56.000000,6.000000,6.000000,6.000000,34516.000000,2517.000000,34516.000000,3.397000,18484.000000,139.000000,3.714000,0.999000

In [10]:
df.info()
print(df.isnull().sum())

<class 'pandas.DataFrame'>
RangeIndex: 10127 entries, 0 to 10126
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   status_cliente           10127 non-null  str
 1   idade                    10127 non-null  int64
 2   genero                   10127 non-null  str
 3   dependentes              10127 non-null  int64
 4   escolaridade             8608 non-null   str
 5   estado_civil             9378 non-null   str
 6   faixa_renda              9015 non-null   str
 7   categoria_cartao         10127 non-null  str
 8   meses_como_cliente       10127 non-null  int64
 9   total_produtos           10127 non-null  int64
 10  meses_inativo_12m        10127 non-null  int64
 11  contatos_12m             10127 non-null  int64
 12  limite_credito           10127 non-null  float64
 13  saldo_rotativo           10127 non-null  int64
 14  limite_disponivel_medio  10127 non-null  float64
 15  var_valor_q4_q1          10127 non-null  float64
 16  valor_total_transacoes   10127 non-null  int64
 17  qtd_total_transacoes     10127 non-null  int64
 18  var_qtd_q4_q1            10127 non-null  float64
 19  taxa_utilizacao_credito  10127 non-null  float64
dtypes: float64(5), int64(9), str(6)
memory usage: 2.0 MB
status_cliente                0
idade                         0
genero                        0
dependentes                   0
escolaridade               1519
estado_civil                749
faixa_renda                1112
categoria_cartao              0
meses_como_cliente            0
total_produtos                0
meses_inativo_12m             0
contatos_12m                  0
limite_credito                0
saldo_rotativo                0
limite_disponivel_medio       0
var_valor_q4_q1               0
valor_total_transacoes        0
qtd_total_transacoes          0
var_qtd_q4_q1                 0
taxa_utilizacao_credito       0
dtype: int64

In [13]:
df = df.dropna()
print("Tamanho atual do dataset (linhas, colunas):", df.shape)
print("Valores nulos por coluna:")
print(df.isnull().sum())

Tamanho atual do dataset (linhas, colunas): (7081, 20)
Valores nulos por coluna:
status_cliente             0
idade                      0
genero                     0
dependentes                0
escolaridade               0
estado_civil               0
faixa_renda                0
categoria_cartao           0
meses_como_cliente         0
total_produtos             0
meses_inativo_12m          0
contatos_12m               0
limite_credito             0
saldo_rotativo             0
limite_disponivel_medio    0
var_valor_q4_q1            0
valor_total_transacoes     0
qtd_total_transacoes       0
var_qtd_q4_q1              0
taxa_utilizacao_credito    0
dtype: int64

In [16]:
os.makedirs('dataset/processed', exist_ok=True)

caminho_arquivo = 'data/processed/dataset_limpo.csv'
df.to_csv(caminho_arquivo, index=False)

print(f"Dataset salvo com sucesso em: {caminho_arquivo}")

Dataset salvo com sucesso em: data/processed/dataset_limpo.csv